ingress:
  read:
    enabled: true
    className: "nginx"
    annotations: {}
    hosts:
      - host: keto.polyflix.local
        paths:
          - path: /read
            pathType: Prefix
    tls: []
  write:
    enabled: true
    className: "nginx"
    annotations:
    hosts:
      - host: keto.polyflix.local
        paths:
          - path: /write
            pathType: Prefix
    tls: []
deployment:
  extraVolumeMounts:
    - name: namespaces
      mountPath: /etc/keto-namespaces/
  extraVolumes:
    - name: namespaces
      configMap:
        name: keto-namespaces

keto:
  config:
    dsn: memory
    namespaces:
      location: file:///etc/keto-namespaces/namespaces.keto.ts