mode: standalone
defaultBuckets: "videos subtitles images"
auth:
  rootUser: polyflix
  rootPassword: polyflix
persistence:
  size: 1Gi

extraEnvVars:
  - name: MINIO_NOTIFY_KAFKA_ENABLE_VIDEO
    value: "true"
  - name: MINIO_NOTIFY_KAFKA_BROKERS_VIDEO
    value: "kafka-0.kafka-headless:9092"
  - name: MINIO_NOTIFY_KAFKA_TOPIC_VIDEO
    value: "polyflix.minio.video"

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: console.minio.polyflix.local

apiIngress:
  enabled: true
  ingressClassName: nginx
  hostname: minio

service:
  ports:
    api: 8080