apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polyflix-gateway
spec:
  ingressClassName: nginx
  rules:
  - host: polyflix.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: gateway
            port:
              number: 80
