fullnameOverride: quizz

image:
  repository: ghcr.io/polyflix/quizz
  tag: main

extraEnvVars:
  - name: "NEST_PROFILE"
    value: dev
  - name: "NEST_KAFKA_CLIENT_BROKERS"
    value: kafka-0.kafka-headless:9092
  - name: "NEST_SERVER_PORT"
    value: 8080
  - name: NEST_DATABASE_PSQL_URL
    value: "postgres://postgres:polyflix@postgres:5432/video"

migrations:
  enabled: true
  extraEnvVars:
    - name: POSTGRES_URL
      value: "postgres://postgres:polyflix@postgres:5432/quizz"

probes:
  liveness:
    path: /v2.0.0/health
  readiness:
    path: /v2.0.0/health
