fullnameOverride: user

image:
  repository: ghcr.io/polyflix/user
  tag: main

extraEnvVars:
  - name: SERVER_PORT
    value: 8080
  - name: SPRING_PROFILES_ACTIVE
    value: dev
  - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
    value: http://keycloak/realms/Polyflix
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://postgres:5432/usermanagement
  - name: SPRING_DATASOURCE_USERNAME
    value: postgres
  - name: SPRING_DATASOURCE_PASSWORD
    value: polyflix
  - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
    value: kafka-0.kafka-headless:9092


probes:
  liveness:
    path: /actuator/health
    initialDelaySeconds: 60
  readiness:
    path: /actuator/health
    initialDelaySeconds: 60
